name: Search-Flight-UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"  # or whatever version you prefer

      - name: Install dependencies
        run: |
          npm ci  

      - name: Type check with TypeScript
        run: |
          npx tsc --noEmit  # This will run TypeScript's type checker

      - name: Run frontend tests
        run: |
          npm test  # This assumes you have a test script in your package.json

      - name: Code coverage
        run: |
          npm test --coverage  # This assumes you have a coverage script in your package.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}


